### ISSUE TITLE
[question] Should ID be necessary in this case?

### ISSUE THREAD

**Issue by ale1313** [EricRCorral/challenge-puzzle-rick-and-morty#11]
I get that you're rendering this component in multiple instances. Probably the property `key` is more appropiate?

https://github.com/EricRCorral/challenge-puzzle-rick-and-morty/blob/f1f6cbd37354c6abc01560d2439244573d496a6e/src/components/card/card.tsx#L18

**Comment by EricRCorral** [comment]
Yes, because modal works with an ID
