### ISSUE TITLE
[question] Type validation

### ISSUE THREAD

**Issue by ale1313** [EricRCorral/challenge-puzzle-rick-and-morty#16]
Uhm, do you actually have an empty string for this value? Why is that?

https://github.com/EricRCorral/challenge-puzzle-rick-and-morty/blob/f1f6cbd37354c6abc01560d2439244573d496a6e/src/components/card/card.tsx#L38

**Comment by EricRCorral** [comment]
Because in fact some characters has type "" when they came from the query
