### ISSUE TITLE
[question] Shouldn't the item be an element of Data?

### ISSUE THREAD

**Issue by ale1313** [EricRCorral/challenge-puzzle-rick-and-morty#18]
Is it possible to fix this any? I guess it should be

https://github.com/EricRCorral/challenge-puzzle-rick-and-morty/blob/f1f6cbd37354c6abc01560d2439244573d496a6e/src/components/card/card.tsx#L59

**Comment by EricRCorral** [comment]
Yes now I has destructured the item object and created his own interface
